# Generated by Django 5.0 on 2023-12-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=255)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('tipe', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=10)),
            ],
        ),
    ]
